---
- hosts : all
  gather_facts: false
  connection: network_cli
  tasks: 
    - name: Show run on device
      ios_command:
        commands:
          - show run
      register: config

- hosts: all
  gather_facts: false
  tasks:
    - name: Save output to ~/home/netserv/Documents/
      copy:
        content: "{{config.stdout[0]}}"
        dest:  ~/home/netserv/Documents/testfile
